#МоиЛекции #ЯзыкПрограммирования  #Python 

При программировании на Python мы можем столкнуться с двумя типами ошибок. Первый тип представляют **синтаксические ошибки** (**syntax error**). Они появляются в результате нарушения синтаксиса языка программирования при написании исходного кода. При работе в какой-либо среде разработки, например, в **PyCharm**, **IDE** сама может отслеживать синтаксические ошибки и каким-либо образом их выделять.

Второй тип ошибок представляют **ошибки выполнения** (**runtime error**). Они появляются в уже в процессе выполнения программы. Подобные ошибки еще называются *исключениями*. Например, в прошлых темах мы рассматривали преобразование строки в число:

```python
string = "5"
number = int(string)
print(number)
```

Данный скрипт успешно выполнится, так как строка "`5`" вполне может быть конвертирована в число. Однако возьмем другой пример:

```python
string = "hello"
number = int(string)
print(number)
```

При выполнении этого скрипта будет выброшено исключение **ValueError**, так как строку "`hello`" нельзя преобразовать в число:

```
ValueError: invalid literal for int() with base 10: 'hello'
```

С одной стороны, здесь очевидно, что строка не представляет число, но мы можем иметь дело с вводом пользователя, который также может ввести не совсем то, что мы ожидаем:

```python
string = input("Введите число: ")
number = int(string)
print(number)
```

При возникновении исключения работа программы прерывается, и чтобы избежать подобного поведения и обрабатывать исключения в Python есть конструкция `try..except`.

### try..except

Конструкция `try..except` имеет следующее формальное определение:

```python
try:
    инструкции
except [Тип_исключения]:
    инструкции
```

Весь основной код, в котором потенциально может возникнуть исключение, помещается после ключевого слова `try`. Если в этом коде генерируется исключение, то работа кода в блоке `try` прерывается, и выполнение переходит в блок `except`.

После ключевого слова `except` опционально можно указать, какое исключение будет обрабатываться (например, `ValueError` или `KeyError`). После слова `except` на следующей стоке идут инструкции блока `except`, выполняемые при возникновении исключения.

Рассмотрим обработку исключения на примере преобразовании строки в число:

```python
try:
    number = int(input("Введите число: "))
    print("Введенное число:", number)
except:
    print("Преобразование прошло неудачно")
print("Завершение программы")
```

Вводим строку:

```python
Введите число: hello
Преобразование прошло неудачно
Завершение программы
```

Как видно из консольного вывода, при вводе строки вывод числа на консоль не происходит, а выполнение программы переходит к блоку `except`.

Вводим правильное число:

```
Введите число: 22
Введенное число: 22
Завершение программы
```

Теперь все выполняется нормально, исключение не возникает, и соответственно блок `except` не выполняется.

### Блок finally

При обработке исключений также можно использовать необязательный блок `finally`. Отличительной особенностью этого блока является то, что он выполняется вне зависимости, было ли сгенерировано исключение:

```python
try:
    number = int(input("Введите число: "))
    print("Введенное число:", number)
except:
    print("Преобразование прошло неудачно")
finally:
    print("Блок try завершил выполнение")
print("Завершение программы")
```

Как правило, блок `finally` применяется для освобождения используемых ресурсов, например, для закрытия файлов.

Стоит отметить, что блок `finally` не обрабатывает исключения, и если мы используем этот блок без блока `except`, то при возникновении ошибки приложение аварийно завершится, как в следующем случае при делении числа на ноль:

```python
try:
    number = 3/0    # генерирует исключение ZeroDivisionError
    print(number)
finally:
    print("Блок try завершил выполнение")
print("Завершение программы")
```

---
## Ссылки

1. [Конструкция try...except...finally](https://metanit.com/python/tutorial/2.11.php)
2. [[Вопросы для самопроверки. Конструкция try...except...finally]]

---

| [[Абстрактные классы и методы\|Предыдущая лекция]] | [[Except и обработка разных типов исключений\|Следующая лекция]] |
| -------------------------------------------------- | ---------------------------------------------------------------- |
